# -*- coding: utf-8 -*-
"""Exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQRqrn6v4Y4GnyFcoRCXl4zcB-TuWS7p
"""

balance = float(input("What is your balance?"))

if balance:
  print("You have some money!")
  print(f"Your balance is {balance}")

amount = float(input("What is your balance?"))

if amount <= 0:
  print("You are in debt")

elif amount < 2000:
  print("You are not in debt")
  print("You cannot take loan")
else:
  print("You are not in debt")
  print("You can take loan")

balances = float(input("What is your balance?"))
age = int(input("What is your age?"))
input_has_job = input("Do you have a job? (Yes/No)")

if input_has_job == "Yes" or input_has_job == "y":
  have_job = True
else:
  have_job = False

if age > 18 and age <60:
  print("You can have some special benefits")

if balances <= 0:
  print("You are in debt")
else:
  print("You are not in debt")
  if balances < 2000 or age < 18 or age > 60 or not have_job:
    print("You cannot take loan")
  else:
    print("You can take loan")

print("Grocery list program")
grocery_list = []
user_input = None

while user_input != "end":
  user_input = input("Input an item(type 'end' to finish)")
  if user_input != "end":
    grocery_list.append(user_input)

print("Here is your grocery list!")
i = 0

while i < len(grocery_list):
  print(f"{grocery_list[i]}")
  i = i + 1

print("Grocery list program")
grocery_list = []

while True:
  user_input = input("Input an item(type 'end' to finish)")
  if user_input == "end":
    break
  grocery_list.append(user_input)
e
print("Here is your grocery list!")

for item in grocery_list:
  print(item)

def find_in_list(some_item, some_list):
  for item in some_list:
    if item == some_item:
      print(f"{some_item} is in the list")
      break
  else:
    print(f"{some_item} is not in the list")

find_in_list("bread", grocery_list)

class BankAccount:
  def __init__(self, name, number, balance):
    self.name = name
    self.number = number
    self.balance = balance

  def deposit(self, amount):
    self.balance += amount

  def withdraw(self, amount):
    if self.balance >= amount:
      self.balance -= amount
    else:
      print("Insufficient Funds")

  def info(self):
    return f"{self.name} {self.number} {self.balance}"



Account1 = BankAccount("sameer", "001435467", 25000)
Account2 = BankAccount("Ravi", "001435224", 30000)

print(Account1.name)
print(Account2.info())
Account2.deposit(20000)
Account2.withdraw(100000)
print(Account2.info())

import numpy as np

data = [67, 65, 43, 39, 89, 55, 67, 30, 44, 55, 60, 25, 50, 55, 60, 58, 34, 55]
array = np.array(data)
mean = np.mean(array)
print(f'Grade: {mean:.2f}')

arithmetic_mean = np.mean(data)
bincount = np.bincount(data)
mode = bincount.argmax()
std_dev = np.std(data)
median = np.median(data)
sum = np.sum(data)
min = np.min(data)
max = np.max(data)

print(f'mean:{arithmetic_mean:.2f}')
print(f'Bin count:{bincount}')
print(f'Mode:{mode}')
print(f'std dev:{std_dev:.2f}')
print(f'median:{median}')
print(f'sum:{sum}')
print(f'min:{min}')
print(f'max:{max}')

outlier_mask = (np.abs(data - mean) > 7*std_dev) | (data < 0)

data_with_nan = data.copy()
data_with_nan[outlier_mask] = np.nan

new_array = np.arange(0,11,2)
print(new_array)

new_arr = np.linspace(0.1, 0.5, 5)
print(new_arr)

# Array copy

original_array = np.array([2, 4, 6, 8, 10])

copy_array = original_array.copy()

print(f'THis is original array : {original_array}')
print(f'THis is copy array : {copy_array}')

# Array view

original_array = np.array([2, 4, 6, 8, 10])

view_array = original_array.view()

print(f'original array : {original_array}')
print(f'view array : {view_array}')

import pandas as pd

column_names = ["Date_of_transaction",
          "Branch_name",
          "Amount_of_sale",
          "Is_active"]

df_one = pd.DataFrame(columns=column_names)

df_one

default_data = {
    "Date_of_transaction": ["Jan 1", "Jan 2"],
    "Branch_name": ["Branch A", "Branch B"],
    "Amount_of_sale": [500, 600],
    "Is_active" : [True, False]
}
df_default_data = pd.DataFrame(default_data)

df_default_data

# combining dataframes

df_combined = pd.concat([df_one, df_default_data])
df_combined.reset_index(drop=True, inplace=True)

df_default_data.iloc[0:4, 0:2]

# Cleaning data

df_hotel = pd.read_csv("hotel_bookings.csv")

df_hotel.isnull().sum()

df_hotel.drop(["company", "agent"], axis=1, inplace=True)

df_hotel.dropna(inplace=True)

df_hotel.duplicated().sum()
df_hotel.drop_duplicates(inplace=True)
df_hotel.reset_index(drop=True, inplace=True)

df_hotel['reservation_status_date'] = pd.to_datetime(df_hotel['reservation_status_date'])
df_hotel['year'] = df_hotel['reservation_status_date'].dt.year
df_hotel['month'] = df_hotel['reservation_status_date'].dt.month
df_hotel['day'] = df_hotel['reservation_status_date'].dt.day
df_hotel.drop(('reservation_status_date'), inplace=True, axis=1)

# Correlation Matrix

cat_cols = [col for col in df_hotel.columns if df_hotel[col].dtype == 'object']

cat_df = df_hotel[cat_cols]

for col in cat_df.columns:
  print(f'{col}: \n{cat_df[col].unique()}\n')

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

cat_df['country'] = le.fit_transform(cat_df['country'])
cat_df['hotel'] = le.fit_transform(cat_df['hotel'])

cat_df = pd.get_dummies(data=cat_df, columns=["arrival_date_month", "meal", "market_segment", "distribution_channel",
                                             "reserved_room_type", "assigned_room_type", "customer_type",
                                             "deposit_type", "reservation_status"], dtype=int)

num_df = df_hotel.select_dtypes(include=['int64', 'float64'])

final_df = pd.concat([cat_df, num_df], axis=1)
corr_matrix = final_df.corr().abs()
