# -*- coding: utf-8 -*-
"""Exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQRqrn6v4Y4GnyFcoRCXl4zcB-TuWS7p
"""

balance = float(input("What is your balance?"))

if balance:
  print("You have some money!")
  print(f"Your balance is {balance}")

amount = float(input("What is your balance?"))

if amount <= 0:
  print("You are in debt")

elif amount < 2000:
  print("You are not in debt")
  print("You cannot take loan")
else:
  print("You are not in debt")
  print("You can take loan")

balances = float(input("What is your balance?"))
age = int(input("What is your age?"))
input_has_job = input("Do you have a job? (Yes/No)")

if input_has_job == "Yes" or input_has_job == "y":
  have_job = True
else:
  have_job = False

if age > 18 and age <60:
  print("You can have some special benefits")

if balances <= 0:
  print("You are in debt")
else:
  print("You are not in debt")
  if balances < 2000 or age < 18 or age > 60 or not have_job:
    print("You cannot take loan")
  else:
    print("You can take loan")

print("Grocery list program")
grocery_list = []
user_input = None

while user_input != "end":
  user_input = input("Input an item(type 'end' to finish)")
  if user_input != "end":
    grocery_list.append(user_input)

print("Here is your grocery list!")
i = 0

while i < len(grocery_list):
  print(f"{grocery_list[i]}")
  i = i + 1

print("Grocery list program")
grocery_list = []

while True:
  user_input = input("Input an item(type 'end' to finish)")
  if user_input == "end":
    break
  grocery_list.append(user_input)
e
print("Here is your grocery list!")

for item in grocery_list:
  print(item)

def find_in_list(some_item, some_list):
  for item in some_list:
    if item == some_item:
      print(f"{some_item} is in the list")
      break
  else:
    print(f"{some_item} is not in the list")

find_in_list("bread", grocery_list)

class BankAccount:
  def __init__(self, name, number, balance):
    self.name = name
    self.number = number
    self.balance = balance

  def deposit(self, amount):
    self.balance += amount

  def withdraw(self, amount):
    if self.balance >= amount:
      self.balance -= amount
    else:
      print("Insufficient Funds")

  def info(self):
    return f"{self.name} {self.number} {self.balance}"



Account1 = BankAccount("sameer", "001435467", 25000)
Account2 = BankAccount("Ravi", "001435224", 30000)

print(Account1.name)
print(Account2.info())
Account2.deposit(20000)
Account2.withdraw(100000)
print(Account2.info())

